name: sql-ghau-ri-40393
on: 
  workflow_dispatch:
    inputs:
      target-URL:
        description: "Enter Target URL to Scan"
        required: false
      target-Request:
        description: "Paste Request here"
        required: false
        
        
jobs:

  scan:
    name: ghauri-scan
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v5.0.0
      
    - name: Scan the Target
      run: |
        target_url="${{ inputs.target-URL }}"
        target_req="${{ inputs.target-Request }}"
        sudo apt update
        sudo apt install git python3-pip -y
        git clone https://github.com/r0oth3x49/ghauri.git
        cd ghauri
        python3 -m pip install --upgrade -r requirements.txt
        sudo python3 setup.py install
        echo "Ghauri Help Menu"
        ghauri --help
        if [[ -n "$target_url" ]]; then
          echo "Scanning URL"
          ghauri -u "$target_url" -H "Intigriti-Bug-Bounty: ID-10226f54c28c4a43b722424920c709dff1a49067004e8989d3dde9f4b7136ffa" --delay 1
        elif [[ -n "$target_req" ]]; then
          echo "No URL given, scanning request"
          ghauri -r "$target_req" -H "X-HackerOne-Research: ss82" --delay 1
        else
          echo "Error: Both URL and request inputs are empty. Please provide at least one."
        exit 1
        fi

#"X-HackerOne-Research: ss82"










